### PR TITLE
initial commit for polysysgen

### PR DESCRIPTION
**Pull request by rusydi**
Hi Marc,

This is the shell script to generate random overdefined equations and its corresponding solution. The concept is to create a .cpp file that uses available data type (polynomial, monomial, finite field element) in m4gb to generate the random system so that it won't need any external packages/libraries. The input file format follows the default input format (we had this format previously in the SVN repo).

PS : I know that this is a bit cheating. But if I had to write it in pure python, I must also implement GF(p) and GF(2^n) arithmetic in the python script itself. These are doable but I try to minimize duplication of work since both are already available in m4gb.

### CODE REVIEW

**Comment by rusydi** [comment]
Btw, is the location of the file alright ? Should I put it in another folder ?

**Comment by cr-marcstevens** [comment]
I suggest to put the c++ source file in `solver/generator.cpp` and let it include `config.hpp`.
Then you can use the same mechanism to control `FIELDSIZE` and `MAXVARS` as for openf4 in `Makefile.am`.
The shell script just has to call make appropriately and then the generator binary.

**Comment by cr-marcstevens** [comment]
Please check the new branch 'generator' of cr-marcstevens/m4gb.
I added a slightly modified `solver/generator.cpp` and the necessary stuff to Makefile.am.
You can build the generator with `MAXVARS=20 FIELDSIZE=31 make generator`.
Still, the generator needs to be adjusted for runtime parameters: nr equations, degree, output files.

**Comment by rusydi** [comment]
Hi Marc,
Thanks for the example in branch "generator". I will resolve the conflict and parametrised the format for output filename a bit late tonight.

**Comment by cr-marcstevens** [comment]
A few comments:
- I suggest to give the NPOLYS via command line instead compile time, to reduce the need to compile binaries.
- DEG is a compile time option, so should be reflected in the executable name.
Question:
- Does DEG ?= 2 work correctly through automake? Have you tried and checked some cases?

**Comment by rusydi** [comment]
Hi Marc,
Should generator.cpp and polysysgen.sh must be moved from solver/ to src/ as well ?

**Comment by rusydi** [comment]
Thanks for the comment. I simply remove DEG ?= 2 from the Makefile.am because calling polysysgen.sh without setting the degree should already assign DEG=2 by default.

**Pull request merged**
